// <auto-generated />
using IdleGod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdleGod.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181217202727_timeradded")]
    partial class timeradded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdleGod.Models.Player", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Experience");

                    b.Property<int>("Level");

                    b.Property<int>("Money");

                    b.Property<int>("Salary");

                    b.Property<int>("SalaryBumpPrice");

                    b.Property<int>("Timer");

                    b.Property<int>("TimerDecreasePrice");

                    b.Property<int>("XpBumpPrice");

                    b.Property<int>("XpGain");

                    b.Property<int>("XpToLevel");

                    b.HasKey("UserId");

                    b.ToTable("Player");

                    b.HasData(
                        new { UserId = "5b9ee498-aad6-420b-8aaf-d8943f8cec11", Experience = 0, Level = 1, Money = 0, Salary = 25, SalaryBumpPrice = 750, Timer = 20, TimerDecreasePrice = 10000, XpBumpPrice = 500, XpGain = 10, XpToLevel = 500 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
